/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './patterns/**/*.php',
    './templates/**/*.html',
    './parts/**/*.html',
    './assets/js/**/*.js',
    // DB content dump — generated by `npm run dump` before each build
    './bin/content-scan.html',
  ],

  safelist: [
    // ─── Display ────────────────────────────────────────────────────────────
    'block', 'inline-block', 'inline', 'flex', 'inline-flex',
    'grid', 'inline-grid', 'hidden',

    // ─── Flex ───────────────────────────────────────────────────────────────
    'flex-row', 'flex-col', 'flex-row-reverse', 'flex-col-reverse',
    'flex-wrap', 'flex-nowrap', 'flex-wrap-reverse',
    'flex-1', 'flex-auto', 'flex-initial', 'flex-none',
    'shrink', 'shrink-0', 'grow', 'grow-0',
    '!flex-nowrap',

    // ─── Grid ───────────────────────────────────────────────────────────────
    {
      pattern: /^grid-cols-(1|2|3|4|5|6|7|8|9|10|11|12|none)$/,
      variants: ['sm', 'md', 'lg', 'xl'],
    },
    {
      pattern: /^col-span-(1|2|3|4|5|6|7|8|9|10|11|12|full)$/,
      variants: ['sm', 'md', 'lg', 'xl'],
    },
    {
      pattern: /^col-(auto|start-\d|end-\d)$/,
      variants: ['sm', 'md', 'lg', 'xl'],
    },

    // ─── Justify / Align ────────────────────────────────────────────────────
    'justify-start', 'justify-end', 'justify-center',
    'justify-between', 'justify-around', 'justify-evenly',
    'items-start', 'items-end', 'items-center',
    'items-stretch', 'items-baseline',
    'self-start', 'self-end', 'self-center', 'self-stretch',
    'place-items-center', 'place-content-center',
    '!items-stretch',

    // ─── Gap ────────────────────────────────────────────────────────────────
    {
      pattern: /^(!?gap-(x-|y-)?(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24))$/,
      variants: ['sm', 'md', 'lg'],
    },
    '!gap-0', '!gap-2', '!gap-3', '!gap-4', '!gap-6',

    // ─── Padding ────────────────────────────────────────────────────────────
    {
      pattern: /^p[xytblr]?-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32)$/,
      variants: ['sm', 'md', 'lg'],
    },
    {
      pattern: /^!p[xytblr]?-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32)$/,
    },

    // ─── Margin ─────────────────────────────────────────────────────────────
    {
      pattern: /^-?m[xytblr]?-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|auto)$/,
      variants: ['sm', 'md', 'lg'],
    },
    {
      pattern: /^!-?m[xytblr]?-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24)$/,
    },
    '!-ml-10', '!-mt-14', '!mb-0', '!mt-10',

    // ─── Width ──────────────────────────────────────────────────────────────
    'w-full', 'w-auto', 'w-screen', 'w-fit',
    'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-3/4', 'w-1/5', 'w-2/5', 'w-3/5', 'w-4/5',
    'w-5/12', 'w-7/12',
    {
      pattern: /^w-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|48|56|64|72|80|96)$/,
      variants: ['sm', 'md', 'lg'],
    },
    {
      pattern: /^max-w-(xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|full|none|prose)$/,
      variants: ['sm', 'md', 'lg'],
    },
    // Fractional max-width used in patterns (JIT)
    'max-w-5/12', 'max-w-7/12', 'max-w-1/2', 'max-w-3/4',
    'md:w-4/12', 'lg:!max-w-5/12',

    // ─── Height ─────────────────────────────────────────────────────────────
    'h-full', 'h-auto', 'h-screen', 'h-fit',
    {
      pattern: /^(!?h-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|48|56|64|72|80|96))$/,
    },
    'min-h-0', 'min-h-full', 'min-h-screen',
    {
      pattern: /^min-h-(16|24|32|40|48|56|64|72|80|96)$/,
    },
    'min-h-96', '!h-full',

    // ─── Typography ─────────────────────────────────────────────────────────
    'text-xs', 'text-sm', 'text-base', 'text-lg',
    'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl', 'text-6xl',
    '!text-3xl',
    'font-thin', 'font-light', 'font-normal', 'font-medium',
    'font-semibold', 'font-bold', 'font-extrabold', 'font-black',
    'text-left', 'text-center', 'text-right', 'text-justify',
    'leading-none', 'leading-tight', 'leading-snug', 'leading-normal',
    'leading-relaxed', 'leading-loose',
    'uppercase', 'lowercase', 'capitalize', 'normal-case',
    'truncate', 'text-ellipsis',
    'underline', 'line-through', 'no-underline',
    'italic', 'not-italic',
    'whitespace-nowrap', 'whitespace-normal', 'whitespace-pre-wrap',

    // ─── Colors (paired with theme palette) ─────────────────────────────────
    // Text
    'text-white', 'text-black',
    {
      pattern: /^text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    // Background
    'bg-white', 'bg-black', 'bg-transparent',
    {
      pattern: /^bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    // Border
    {
      pattern: /^border-(slate|gray|red|blue|green|yellow)-(200|300|400|500|600)$/,
    },

    // ─── Border ─────────────────────────────────────────────────────────────
    'border', 'border-0', 'border-2', 'border-4',
    'border-t', 'border-b', 'border-l', 'border-r',
    'rounded', 'rounded-sm', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-full', 'rounded-none',

    // ─── Shadow ─────────────────────────────────────────────────────────────
    'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-none',

    // ─── Overflow ───────────────────────────────────────────────────────────
    'overflow-hidden', 'overflow-visible', 'overflow-auto', 'overflow-scroll',
    'overflow-x-hidden', 'overflow-y-hidden', 'overflow-x-auto', 'overflow-y-auto',

    // ─── Position ───────────────────────────────────────────────────────────
    'static', 'relative', 'absolute', 'fixed', 'sticky',
    'inset-0', 'inset-x-0', 'inset-y-0',
    'top-0', 'right-0', 'bottom-0', 'left-0',

    // ─── Z-index ────────────────────────────────────────────────────────────
    'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50',

    // ─── Opacity ────────────────────────────────────────────────────────────
    {
      pattern: /^opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|100)$/,
    },

    // ─── Transitions ────────────────────────────────────────────────────────
    'transition', 'transition-all', 'transition-colors', 'transition-opacity',
    'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300',
    'ease-in', 'ease-out', 'ease-in-out',

    // ─── Cursor ─────────────────────────────────────────────────────────────
    'cursor-pointer', 'cursor-default', 'cursor-not-allowed',

    // ─── Pointer events ─────────────────────────────────────────────────────
    'pointer-events-none', 'pointer-events-auto',

    // ─── Object fit ─────────────────────────────────────────────────────────
    'object-cover', 'object-contain', 'object-fill', 'object-center', 'object-top',

    // ─── Misc ───────────────────────────────────────────────────────────────
    'sr-only', 'not-sr-only',
    'select-none', 'select-text',
    'list-none', 'list-disc', 'list-decimal',
    'space-y-0', 'space-y-1', 'space-y-2', 'space-y-4', 'space-y-6', 'space-y-8',
    'space-x-0', 'space-x-1', 'space-x-2', 'space-x-4',
  ],

  theme: {
    extend: {
      maxWidth: {
        '1/2':  '50%',
        '1/3':  '33.333333%',
        '2/3':  '66.666667%',
        '1/4':  '25%',
        '3/4':  '75%',
        '1/5':  '20%',
        '2/5':  '40%',
        '3/5':  '60%',
        '4/5':  '80%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12':'83.333333%',
        '11/12':'91.666667%',
      },
    },
  },

  plugins: [],
};
